### ISSUE TITLE
Visual FoxPro Main Screen Won't Open

### ISSUE THREAD

**Issue by peytontodd** [VFPX/VFPXIssues#2]
Yes, I know Visual FoxPro (VFP) is no longer supported or even sold by Microsoft, but everything I do is in that format, and I was hit by a virus that disabled it. I'm hoping someone out there knows the language well enough, or knows where to send me for an answer (all the usual users groups seem to have folded).

At least the best guess as to the cause of the problem is that it was caused by a virus, which tech support at Geek Squad managed to remove, (thus fixing several other weird behaviors the computer suddenly manifested), but this particular damage done presumably by the virus remains.

The problem? Normally when one opens VFP, one sees a main screen where all results appear, including BROWSE windows (spreadsheet-like views of database files), plus a Command Window (for typing in commnds (such as USE <dbfname> and BROWSE). But now only the Command Window opens. No Main Window. It still obeys commands (one can open a DBF file and list its contents to the printer), but one can't really work without the Main Window. 

![Capture](https://user-images.githubusercontent.com/11637058/78997185-0ca62980-7b14-11ea-8df2-ddb053151bc7.GIF)

I installed this copy of VFP initially to two computers - my new Win 10 desktop and my Win 10 laptop - by copying it over via PCMover from its current installation on a Win 7 desktop. It was working fine on both of them, and it still is on the laptop. But when I reinstalled it onto the Win 10 desktop by the same method (PCMover) the problem remained, even though it works in the ways I just described.

For those who know VFP: I've tried _SCREEN.Visible=.T. and _SCREEN.Show(), both in the Command Window and in the CONFIG.FPW file, but they didn't fix it.

Are there any VFP programmers out there who can help me with a solution or know where I might find one?

Thanks in advance for your help.

The attached file, if it makes it, should show what the screens should look like.

**Comment by rschummer** [comment]
This issues section is really for issues related to VFPX, not for general Visual FoxPro issues. My recommendation is for your to visit Foxite.com or LevelExtreme.com where numerous VFP developer exchange ideas and solve problems.

That said, I would first rename the FoxUser.DBF and FoxUser.FPT files used by the instance of VFP. This will allow VFP to create a new one. I suggest this to remove any possibility of corruption causing the problem. 

It is also possible the window is off the monitor. Does the VFP icon show up on the Windows Taskbar? If so, Alt+spacebar to show the app system menu, select Move and use the arrow keys to bring the main VFP window into view.

If that makes no difference, the I would run the following command from the Windows Command Prompt (run as administrator). Note: you can change to the VFP folder or fully path the EXE.

vfp9.exe /regserver

This will update the registry for core VFP settings. 

More information on VFP parameters via:

vfp9.exe /regserver

![image](https://user-images.githubusercontent.com/6232082/78999978-c2c04200-7b19-11ea-8393-dc9e90b37f65.png)

**Comment by peytontodd** [comment]
Thanks, both for directing me to other sources (I tried, but couldn't find any earlier), and also for the suggestions you made. I tried all of those suggestions, but alas, none succeeded. In the process, though, I discovered some strange behaviors that led me to conclude either the virus was not successfully removed after all, or that it did some lasting damage other than hiding the VFP main screen from me. 

For examples: (1) After finding the existing FOXUSER files, I deleted from their list in the successful search window four that belonged to apps I had written for a client long ago; they deleted successfully, but did not disappear from the search window. And when I would double-click on one of the deleted ones, it opened VFP as though it were still there to respond to double-clicks. (2) Quite often, when I double-click a Shortcut in which I have specified that it should open as administrator - and also when I open as administrator from the Run box that's accessible from the Start menu, I get the message 'Do you want to let this program make changes on your computer?' (which seems to prove, based on my experience, that indeed it is opening it as administrator), the result is that it simply does not open. I wait and wait, and nothing (also, no icon appears on the task bar). Then, when I open VFP from a different Shortcut that has NOT been told to open it as administrator (as I verified by checking its properties), THREE distinct copies of VFP open at once (all three appearing when I right-click the task bar icon that appears.  Another problem, perhaps not related to the virus since it's been with me for some time, is that anything I try to open (e.g. double-clicking a folder, or the app of an icon on the desktop) takes about 30 seconds before it happens (I timed it).

This suggests to me that I need to drop this computer off at Geek Squad to see if they can find what ails it.
