### ISSUE TITLE
VFP 7 _screen disappearance

### ISSUE THREAD

**Issue by bmullaly** [VFPX/VFPXIssues#3]
Still rely on VFP 7 for legacy app(s). Sudden change in basic vfp engine behavior has caused full stop. Can launch foxpro and land in command window, but _screen (window universally presented upon opening every version of vfp) does not open, render or become visible. I can run programs that don't have visuals (i.e. simple file copy) but others (i.e. a form or report) launch in a window that I cannot find or open - the foxpro 'desktop'. Only guess is that vfp 7 has been corrupted, or old desptop pc has issues. This is a first, but would appreciate any ideas or feedback offered. Thanks!

**Comment by DougHennig** [comment]
See https://github.com/VFPX/VFPXIssues/issues/2, both for Rick's suggestion about getting help and with issues about _screen not appearing.
