### ISSUE TITLE
Win 11

### ISSUE THREAD

**Issue by spitfire-joedgama** [VFPX/VFPXIssues#5]
I have a VFP 9 project which has been running since 2000. We had a few problems when we started using WIN 10 which were resolved. Now with WIN 11 the Exe keeps crashing if it has not been used for a while. Sometimes 10 to 15 minutes.

Any help will be appreciated.

Joe

**Comment by DougHennig** [comment]
This is a forum for issues about VFPX, not support for VFP in general. I suggest posting your question on Foxite (and add more detail about what's happening).
